development:
 adapter: postgresql
 database: shoutrflatiron_development
 pool: 5
 timeout: 5000
test:
 adapter: postgresql
 database: shoutrflatiron_test
 pool: 5
 timeout: 5000

production:
 adapter: postgresql
 database: shoutrflatiron_production
 pool: 5
 timeout: 5000